// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_HomePage.h"
#include "screens/ui_TetrisScreen.h"
#include "screens/ui_MemoryScreen.h"
#include "screens/ui_SOSScreen.h"
#include "screens/ui_PorukeScreen.h"
#include "screens/ui_KlavijaturaScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HideBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_527192083);    // assets/Cartoon-HD-Wallpapers-High-Quality-converted-from-jpg.png
LV_IMG_DECLARE(ui_img_klavijatura_icon_80x80_png);    // assets/klavijatura_icon_80x80.png
LV_IMG_DECLARE(ui_img_memory_game_80x80_png);    // assets/memory_game_80x80.png
LV_IMG_DECLARE(ui_img_messages_icon_80x80_png);    // assets/messages_icon_80x80.png
LV_IMG_DECLARE(ui_img_tetris_icon_80x80_png);    // assets/tetris_icon_80x80.png
LV_IMG_DECLARE(ui_img_sos_30x30_png);    // assets/sos_30x30.png
LV_IMG_DECLARE(ui_img_wp2844947_png);    // assets/wp2844947.png
LV_IMG_DECLARE(ui_img_back_button_30x30_png);    // assets/back_button_30x30.png
LV_IMG_DECLARE(ui_img_sos_120x120_png);    // assets/sos_120x120.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
