// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void is_blue_mode(lv_event_t * e);
void roza_boja(lv_event_t * e);
void sos_button_pressed(lv_event_t * e);
void tetris_music_on(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
