// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"


void plava_boja(lv_event_t * e)
{
	// Your code here
}

void roza_boja(lv_event_t * e)
{
	// Your code here
}
