// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void is_blue_mode(lv_event_t * e);
void roza_boja(lv_event_t * e);
void sos_music_on(lv_event_t * e);
void tetris_music_on(lv_event_t * e);
void exit_tetris(lv_event_t * e);
void sos_music_off(lv_event_t * e);
void d_note_event(lv_event_t * e);
void c_note_event(lv_event_t * e);
void e_note_event(lv_event_t * e);
void f_note_event(lv_event_t * e);
void g_note_event(lv_event_t * e);
void a_note_event(lv_event_t * e);
void c2_note_event(lv_event_t * e);
void b_note_event(lv_event_t * e);
void dis_note_event(lv_event_t * e);
void fis_note_event(lv_event_t * e);
void gis_note_event(lv_event_t * e);
void ais_note_event(lv_event_t * e);
void cis_note_event(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
