// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_HomePage = NULL;
lv_obj_t * ui_ColorSwitch = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Poruke = NULL;
lv_obj_t * ui_Memory = NULL;
lv_obj_t * ui_SOS = NULL;
lv_obj_t * ui_Tetris = NULL;
// event funtions
void ui_event_ColorSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        plava_boja(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        roza_boja(e);
    }
}

void ui_event_Poruke(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Poruke1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Poruke1_screen_init);
    }
}

// build funtions

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomePage, lv_color_hex(0x88BADC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColorSwitch = lv_switch_create(ui_HomePage);
    lv_obj_set_width(ui_ColorSwitch, 50);
    lv_obj_set_height(ui_ColorSwitch, 25);
    lv_obj_set_x(ui_ColorSwitch, 121);
    lv_obj_set_y(ui_ColorSwitch, 90);
    lv_obj_set_align(ui_ColorSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ColorSwitch, lv_color_hex(0x6C6161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 119);
    lv_obj_set_y(ui_Label1, 111);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Plava/Roza");

    ui_Poruke = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Poruke, 80);
    lv_obj_set_height(ui_Poruke, 80);
    lv_obj_set_x(ui_Poruke, 50);
    lv_obj_set_y(ui_Poruke, -60);
    lv_obj_set_align(ui_Poruke, LV_ALIGN_CENTER);

    ui_Memory = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Memory, 80);
    lv_obj_set_height(ui_Memory, 80);
    lv_obj_set_x(ui_Memory, -50);
    lv_obj_set_y(ui_Memory, -60);
    lv_obj_set_align(ui_Memory, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Memory, lv_color_hex(0x2E9D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Memory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOS = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_SOS, 80);
    lv_obj_set_height(ui_SOS, 80);
    lv_obj_set_x(ui_SOS, 50);
    lv_obj_set_y(ui_SOS, 40);
    lv_obj_set_align(ui_SOS, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SOS, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tetris = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Tetris, 80);
    lv_obj_set_height(ui_Tetris, 80);
    lv_obj_set_x(ui_Tetris, -50);
    lv_obj_set_y(ui_Tetris, 40);
    lv_obj_set_align(ui_Tetris, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Tetris, lv_color_hex(0xDEE913), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tetris, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ColorSwitch, ui_event_ColorSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Poruke, ui_event_Poruke, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOS, sos_button_pressed, LV_EVENT_ALL, NULL);

}

void ui_HomePage_screen_destroy(void)
{
    if(ui_HomePage) lv_obj_del(ui_HomePage);

    // NULL screen variables
    ui_HomePage = NULL;
    ui_ColorSwitch = NULL;
    ui_Label1 = NULL;
    ui_Poruke = NULL;
    ui_Memory = NULL;
    ui_SOS = NULL;
    ui_Tetris = NULL;

}
