// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomePage
extern void ui_HomePage_screen_init(void);
extern void ui_HomePage_screen_destroy(void);
extern lv_obj_t * ui_HomePage;
extern void ui_event_ColorSwitch(lv_event_t * e);
extern lv_obj_t * ui_ColorSwitch;
extern lv_obj_t * ui_Label1;
extern void ui_event_Poruke(lv_event_t * e);
extern lv_obj_t * ui_Poruke;
extern void ui_event_Memory(lv_event_t * e);
extern lv_obj_t * ui_Memory;
extern void ui_event_SOS(lv_event_t * e);
extern lv_obj_t * ui_SOS;
extern void ui_event_Tetris(lv_event_t * e);
extern lv_obj_t * ui_Tetris;
extern void ui_event_Klavijatura(lv_event_t * e);
extern lv_obj_t * ui_Klavijatura;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

