// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_HOMEPAGE2_H
#define UI_HOMEPAGE2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomePage2
extern void ui_HomePage2_screen_init(void);
extern void ui_HomePage2_screen_destroy(void);
extern lv_obj_t * ui_HomePage2;
extern void ui_event_ColorSwitch1(lv_event_t * e);
extern lv_obj_t * ui_ColorSwitch1;
extern lv_obj_t * ui_Label2;
extern void ui_event_Koraci(lv_event_t * e);
extern lv_obj_t * ui_Koraci;
extern void ui_event_Temperatura(lv_event_t * e);
extern lv_obj_t * ui_Temperatura;
extern void ui_event_SOS1(lv_event_t * e);
extern lv_obj_t * ui_SOS1;
extern void ui_event_VoiceChanger(lv_event_t * e);
extern lv_obj_t * ui_VoiceChanger;
extern void ui_event_Kamera(lv_event_t * e);
extern lv_obj_t * ui_Kamera;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

