// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_HomePage2 = NULL;
lv_obj_t * ui_ColorSwitch1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Koraci = NULL;
lv_obj_t * ui_Temperatura = NULL;
lv_obj_t * ui_SOS1 = NULL;
lv_obj_t * ui_VoiceChanger = NULL;
lv_obj_t * ui_Kamera = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
static lv_obj_t * ui_PrevPageBtn = NULL;
// event funtions
void ui_event_ColorSwitch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        is_blue_mode(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        roza_boja(e);
    }
}

void ui_event_Koraci(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_KoraciScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_KoraciScreen_screen_init);
    }
}

void ui_event_Temperatura(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TemperaturaScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TemperaturaScreen_screen_init);
    }
}

void ui_event_SOS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SOSScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SOSScreen_screen_init);
        sos_music_on(e);
    }
}

void ui_event_VoiceChanger(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoiceChangerScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_VoiceChangerScreen_screen_init);
    }
}

void ui_event_Kamera(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_KameraScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_KameraScreen_screen_init);
    }
}

// build funtions

void ui_HomePage2_screen_init(void)
{
    ui_HomePage2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomePage2, lv_color_hex(0x88BADC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomePage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HomePage2, &ui_img_527192083, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColorSwitch1 = lv_switch_create(ui_HomePage2);
    lv_obj_set_width(ui_ColorSwitch1, 50);
    lv_obj_set_height(ui_ColorSwitch1, 25);
    lv_obj_set_x(ui_ColorSwitch1, 121);
    lv_obj_set_y(ui_ColorSwitch1, 90);
    lv_obj_set_align(ui_ColorSwitch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ColorSwitch1, lv_color_hex(0x6C6161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_HomePage2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 116);
    lv_obj_set_y(ui_Label2, 112);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Decko/Cura");

    ui_Koraci = lv_btn_create(ui_HomePage2);
    lv_obj_set_width(ui_Koraci, 90);
    lv_obj_set_height(ui_Koraci, 90);
    lv_obj_set_x(ui_Koraci, 50);
    lv_obj_set_y(ui_Koraci, -60);
    lv_obj_set_align(ui_Koraci, LV_ALIGN_CENTER);

    ui_Temperatura = lv_btn_create(ui_HomePage2);
    lv_obj_set_width(ui_Temperatura, 90);
    lv_obj_set_height(ui_Temperatura, 90);
    lv_obj_set_x(ui_Temperatura, -50);
    lv_obj_set_y(ui_Temperatura, -60);
    lv_obj_set_align(ui_Temperatura, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Temperatura, lv_color_hex(0x2E9D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temperatura, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOS1 = lv_btn_create(ui_HomePage2);
    lv_obj_set_width(ui_SOS1, 40);
    lv_obj_set_height(ui_SOS1, 40);
    lv_obj_set_x(ui_SOS1, -135);
    lv_obj_set_y(ui_SOS1, 95);
    lv_obj_set_align(ui_SOS1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SOS1, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoiceChanger = lv_btn_create(ui_HomePage2);
    lv_obj_set_width(ui_VoiceChanger, 90);
    lv_obj_set_height(ui_VoiceChanger, 90);
    lv_obj_set_x(ui_VoiceChanger, -50);
    lv_obj_set_y(ui_VoiceChanger, 40);
    lv_obj_set_align(ui_VoiceChanger, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_VoiceChanger, lv_color_hex(0xDEE913), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VoiceChanger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Kamera = lv_btn_create(ui_HomePage2);
    lv_obj_set_width(ui_Kamera, 90);
    lv_obj_set_height(ui_Kamera, 90);
    lv_obj_set_x(ui_Kamera, 50);
    lv_obj_set_y(ui_Kamera, 40);
    lv_obj_set_align(ui_Kamera, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Kamera, lv_color_hex(0x851889), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Kamera, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_HomePage2);
    lv_img_set_src(ui_Image1, &ui_img_289807621);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 50);
    lv_obj_set_y(ui_Image1, 40);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_HomePage2);
    lv_img_set_src(ui_Image7, &ui_img_1995866322);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -50);
    lv_obj_set_y(ui_Image7, -60);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_HomePage2);
    lv_img_set_src(ui_Image8, &ui_img_1108033562);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 50);
    lv_obj_set_y(ui_Image8, -60);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_HomePage2);
    lv_img_set_src(ui_Image9, &ui_img_702957783);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, -49);
    lv_obj_set_y(ui_Image9, 40);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_HomePage2);
    lv_img_set_src(ui_Image10, &ui_img_sos_30x30_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -135);
    lv_obj_set_y(ui_Image10, 95);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* Back button (←) — bottom left, symmetric to SOS */
    ui_PrevPageBtn = lv_btn_create(ui_HomePage2);
    lv_obj_set_size(ui_PrevPageBtn, 40, 40);
    lv_obj_set_x(ui_PrevPageBtn, 135);
    lv_obj_set_y(ui_PrevPageBtn, 95);
    lv_obj_set_align(ui_PrevPageBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_PrevPageBtn, 20, 0);
    lv_obj_set_style_bg_color(ui_PrevPageBtn, lv_color_hex(0x333333), 0);
    lv_obj_t *prev_lbl = lv_label_create(ui_PrevPageBtn);
    lv_label_set_text(prev_lbl, LV_SYMBOL_LEFT);
    lv_obj_center(prev_lbl);
    lv_obj_add_event_cb(ui_PrevPageBtn, ui_event_PrevPage, LV_EVENT_ALL, NULL);

    /* Apply correct background based on current colour mode */
    if(ui_is_pink_mode())
    {
        lv_obj_set_style_bg_img_src(ui_HomePage2, &ui_img_wp2844947_png,
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_img_opa(ui_HomePage2, LV_OPA_COVER,
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_HomePage2, lv_color_hex(0xFF69B4),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_HomePage2, LV_OPA_TRANSP,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    lv_obj_add_event_cb(ui_ColorSwitch1, ui_event_ColorSwitch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Koraci, ui_event_Koraci, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temperatura, ui_event_Temperatura, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOS1, ui_event_SOS1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VoiceChanger, ui_event_VoiceChanger, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Kamera, ui_event_Kamera, LV_EVENT_ALL, NULL);

}

void ui_HomePage2_screen_destroy(void)
{
    if(ui_HomePage2) lv_obj_del(ui_HomePage2);

    // NULL screen variables
    ui_HomePage2 = NULL;
    ui_ColorSwitch1 = NULL;
    ui_Label2 = NULL;
    ui_Koraci = NULL;
    ui_Temperatura = NULL;
    ui_SOS1 = NULL;
    ui_VoiceChanger = NULL;
    ui_Kamera = NULL;
    ui_Image1 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_PrevPageBtn = NULL;

}
