// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"
#include <stdio.h>

lv_obj_t * ui_HomePage = NULL;
lv_obj_t * ui_ColorSwitch = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Poruke = NULL;
lv_obj_t * ui_Memory = NULL;
lv_obj_t * ui_SOS = NULL;
lv_obj_t * ui_Tetris = NULL;
lv_obj_t * ui_Klavijatura = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_PorukeBadge = NULL;
// event funtions
void ui_event_ColorSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        is_blue_mode(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        roza_boja(e);
    }
}

void ui_event_Poruke(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PorukeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PorukeScreen_screen_init);
    }
}

void ui_event_Memory(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MemoryScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MemoryScreen_screen_init);
    }
}

void ui_event_SOS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SOSScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SOSScreen_screen_init);
        sos_music_on(e);
    }
}

void ui_event_Tetris(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TetrisScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TetrisScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        tetris_music_on(e);
    }
}

void ui_event_Klavijatura(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_KlavijaturaScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_KlavijaturaScreen_screen_init);
    }
}

// build funtions

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomePage, lv_color_hex(0x88BADC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HomePage, &ui_img_527192083, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColorSwitch = lv_switch_create(ui_HomePage);
    lv_obj_set_width(ui_ColorSwitch, 50);
    lv_obj_set_height(ui_ColorSwitch, 25);
    lv_obj_set_x(ui_ColorSwitch, 121);
    lv_obj_set_y(ui_ColorSwitch, 90);
    lv_obj_set_align(ui_ColorSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ColorSwitch, lv_color_hex(0x6C6161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 116);
    lv_obj_set_y(ui_Label1, 112);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Decko/Cura");

    ui_Poruke = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Poruke, 90);
    lv_obj_set_height(ui_Poruke, 90);
    lv_obj_set_x(ui_Poruke, 50);
    lv_obj_set_y(ui_Poruke, -60);
    lv_obj_set_align(ui_Poruke, LV_ALIGN_CENTER);

    ui_Memory = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Memory, 90);
    lv_obj_set_height(ui_Memory, 90);
    lv_obj_set_x(ui_Memory, -50);
    lv_obj_set_y(ui_Memory, -60);
    lv_obj_set_align(ui_Memory, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Memory, lv_color_hex(0x2E9D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Memory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOS = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_SOS, 40);
    lv_obj_set_height(ui_SOS, 40);
    lv_obj_set_x(ui_SOS, -135);
    lv_obj_set_y(ui_SOS, 95);
    lv_obj_set_align(ui_SOS, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SOS, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tetris = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Tetris, 90);
    lv_obj_set_height(ui_Tetris, 90);
    lv_obj_set_x(ui_Tetris, -50);
    lv_obj_set_y(ui_Tetris, 40);
    lv_obj_set_align(ui_Tetris, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Tetris, lv_color_hex(0xDEE913), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tetris, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Klavijatura = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_Klavijatura, 90);
    lv_obj_set_height(ui_Klavijatura, 90);
    lv_obj_set_x(ui_Klavijatura, 50);
    lv_obj_set_y(ui_Klavijatura, 40);
    lv_obj_set_align(ui_Klavijatura, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Klavijatura, lv_color_hex(0x851889), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Klavijatura, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image2, &ui_img_klavijatura_icon_80x80_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 50);
    lv_obj_set_y(ui_Image2, 40);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image3, &ui_img_memory_game_80x80_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -50);
    lv_obj_set_y(ui_Image3, -60);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image4, &ui_img_messages_icon_80x80_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 50);
    lv_obj_set_y(ui_Image4, -60);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image5, &ui_img_tetris_icon_80x80_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -50);
    lv_obj_set_y(ui_Image5, 40);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image6, &ui_img_sos_30x30_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -135);
    lv_obj_set_y(ui_Image6, 95);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image1, &ui_img_wp2844947_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /* Notification badge on the Poruke button */
    ui_PorukeBadge = lv_obj_create(ui_Poruke);
    lv_obj_set_size(ui_PorukeBadge, 20, 20);
    lv_obj_align(ui_PorukeBadge, LV_ALIGN_TOP_RIGHT, 0, 0);
    lv_obj_set_style_bg_color(ui_PorukeBadge, lv_color_hex(0xFF0000), 0);
    lv_obj_set_style_radius(ui_PorukeBadge, 10, 0);
    lv_obj_set_style_border_width(ui_PorukeBadge, 0, 0);
    lv_obj_set_style_pad_all(ui_PorukeBadge, 0, 0);
    lv_obj_clear_flag(ui_PorukeBadge, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_t *badge_lbl = lv_label_create(ui_PorukeBadge);
    lv_obj_set_style_text_color(badge_lbl, lv_color_white(), 0);
    lv_obj_center(badge_lbl);
    ui_update_poruke_badge(poruke_get_unread());

    lv_obj_add_event_cb(ui_ColorSwitch, ui_event_ColorSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Poruke, ui_event_Poruke, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Memory, ui_event_Memory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOS, ui_event_SOS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Tetris, ui_event_Tetris, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Klavijatura, ui_event_Klavijatura, LV_EVENT_ALL, NULL);

}

void ui_update_poruke_badge(int count)
{
    if(!ui_PorukeBadge) return;
    if(count <= 0)
    {
        lv_obj_add_flag(ui_PorukeBadge, LV_OBJ_FLAG_HIDDEN);
    }
    else
    {
        char buf[8];
        snprintf(buf, sizeof(buf), "%d", count > 99 ? 99 : count);
        lv_label_set_text(lv_obj_get_child(ui_PorukeBadge, 0), buf);
        lv_obj_clear_flag(ui_PorukeBadge, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_HomePage_screen_destroy(void)
{
    if(ui_HomePage) lv_obj_del(ui_HomePage);

    // NULL screen variables
    ui_HomePage = NULL;
    ui_ColorSwitch = NULL;
    ui_Label1 = NULL;
    ui_Poruke = NULL;
    ui_Memory = NULL;
    ui_SOS = NULL;
    ui_Tetris = NULL;
    ui_Klavijatura = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image1 = NULL;
    ui_PorukeBadge = NULL;

}
