// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_KLAVIJATURASCREEN_H
#define UI_KLAVIJATURASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_KlavijaturaScreen
extern void ui_KlavijaturaScreen_screen_init(void);
extern void ui_KlavijaturaScreen_screen_destroy(void);
extern lv_obj_t * ui_KlavijaturaScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

