// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_KoraciScreen = NULL;
lv_obj_t * ui_BackButtonKoraci = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_BackButtonKoraci(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage2_screen_init);
    }
}

// build funtions

void ui_KoraciScreen_screen_init(void)
{
    ui_KoraciScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_KoraciScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_KoraciScreen, &ui_img_527192083, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonKoraci = lv_imgbtn_create(ui_KoraciScreen);
    lv_obj_set_width(ui_BackButtonKoraci, 30);
    lv_obj_set_height(ui_BackButtonKoraci, 30);
    lv_obj_set_x(ui_BackButtonKoraci, -140);
    lv_obj_set_y(ui_BackButtonKoraci, -100);
    lv_obj_set_align(ui_BackButtonKoraci, LV_ALIGN_CENTER);

    ui_Panel2 = lv_obj_create(ui_KoraciScreen);
    lv_obj_set_width(ui_Panel2, 200);
    lv_obj_set_height(ui_Panel2, 70);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, -69);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xAB0107), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_KoraciScreen);
    lv_img_set_src(ui_Image11, &ui_img_1392414027);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, 69);
    lv_obj_set_y(ui_Image11, -70);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_KoraciScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -64);
    lv_obj_set_y(ui_Label3, -72);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Koraci:");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackButtonKoraci, ui_event_BackButtonKoraci, LV_EVENT_ALL, NULL);

}

void ui_KoraciScreen_screen_destroy(void)
{
    if(ui_KoraciScreen) lv_obj_del(ui_KoraciScreen);

    // NULL screen variables
    ui_KoraciScreen = NULL;
    ui_BackButtonKoraci = NULL;
    ui_Panel2 = NULL;
    ui_Image11 = NULL;
    ui_Label3 = NULL;

}
