// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_KlavijaturaScreen = NULL;
// event funtions

// build funtions

void ui_KlavijaturaScreen_screen_init(void)
{
    ui_KlavijaturaScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_KlavijaturaScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_KlavijaturaScreen_screen_destroy(void)
{
    if(ui_KlavijaturaScreen) lv_obj_del(ui_KlavijaturaScreen);

    // NULL screen variables
    ui_KlavijaturaScreen = NULL;

}
