// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_KameraScreen = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage2_screen_init);
    }
}

// build funtions

void ui_KameraScreen_screen_init(void)
{
    ui_KameraScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_KameraScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_KameraScreen, &ui_img_527192083, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton4 = lv_imgbtn_create(ui_KameraScreen);
    lv_obj_set_width(ui_ImgButton4, 30);
    lv_obj_set_height(ui_ImgButton4, 30);
    lv_obj_set_x(ui_ImgButton4, -140);
    lv_obj_set_y(ui_ImgButton4, -100);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_Button1 = lv_btn_create(ui_KameraScreen);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);

}

void ui_KameraScreen_screen_destroy(void)
{
    if(ui_KameraScreen) lv_obj_del(ui_KameraScreen);

    // NULL screen variables
    ui_KameraScreen = NULL;
    ui_ImgButton4 = NULL;
    ui_Button1 = NULL;

}
