// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_KAMERASCREEN_H
#define UI_KAMERASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_KameraScreen
extern void ui_KameraScreen_screen_init(void);
extern void ui_KameraScreen_screen_destroy(void);
extern lv_obj_t * ui_KameraScreen;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

