// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_KORACISCREEN_H
#define UI_KORACISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_KoraciScreen
extern void ui_KoraciScreen_screen_init(void);
extern void ui_KoraciScreen_screen_destroy(void);
extern lv_obj_t * ui_KoraciScreen;
extern void ui_event_BackButtonKoraci(lv_event_t * e);
extern lv_obj_t * ui_BackButtonKoraci;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

