// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_MEMORYSCREEN_H
#define UI_MEMORYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MemoryScreen
extern void ui_MemoryScreen_screen_init(void);
extern void ui_MemoryScreen_screen_destroy(void);
extern lv_obj_t * ui_MemoryScreen;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ImgButton8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

