// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_MemoryScreen = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
// event funtions

// build funtions

void ui_MemoryScreen_screen_init(void)
{
    ui_MemoryScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MemoryScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_MemoryScreen);
    lv_obj_set_width(ui_Panel2, 270);
    lv_obj_set_height(ui_Panel2, 195);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton8 = lv_imgbtn_create(ui_MemoryScreen);
    lv_obj_set_width(ui_ImgButton8, 347);
    lv_obj_set_height(ui_ImgButton8, 373);
    lv_obj_set_x(ui_ImgButton8, -146);
    lv_obj_set_y(ui_ImgButton8, -105);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

}

void ui_MemoryScreen_screen_destroy(void)
{
    if(ui_MemoryScreen) lv_obj_del(ui_MemoryScreen);

    // NULL screen variables
    ui_MemoryScreen = NULL;
    ui_Panel2 = NULL;
    ui_ImgButton8 = NULL;

}
