// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_MemoryScreen = NULL;
lv_obj_t * ui_ImgButton17 = NULL;
lv_obj_t * ui_Container1 = NULL;
// event funtions
void ui_event_ImgButton17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage_screen_init);
        memory_back(e);
    }
}

// build funtions

void ui_MemoryScreen_screen_init(void)
{
    ui_MemoryScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MemoryScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_MemoryScreen, &ui_img_527192083, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton17 = lv_imgbtn_create(ui_MemoryScreen);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_button_30x30_png, NULL);
    lv_obj_set_width(ui_ImgButton17, 30);
    lv_obj_set_height(ui_ImgButton17, 30);
    lv_obj_set_x(ui_ImgButton17, -142);
    lv_obj_set_y(ui_ImgButton17, -97);
    lv_obj_set_align(ui_ImgButton17, LV_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_MemoryScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 264);
    lv_obj_set_height(ui_Container1, 200);
    lv_obj_set_x(ui_Container1, 11);
    lv_obj_set_y(ui_Container1, 0);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton17, ui_event_ImgButton17, LV_EVENT_ALL, NULL);

}

void ui_MemoryScreen_screen_destroy(void)
{
    if(ui_MemoryScreen) lv_obj_del(ui_MemoryScreen);

    // NULL screen variables
    ui_MemoryScreen = NULL;
    ui_ImgButton17 = NULL;
    ui_Container1 = NULL;

}
