// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Poruke1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions

// build funtions

void ui_Poruke1_screen_init(void)
{
    ui_Poruke1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Poruke1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Poruke1);
    lv_obj_set_width(ui_Keyboard1, 317);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 1);
    lv_obj_set_y(ui_Keyboard1, 55);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

}

void ui_Poruke1_screen_destroy(void)
{
    if(ui_Poruke1) lv_obj_del(ui_Poruke1);

    // NULL screen variables
    ui_Poruke1 = NULL;
    ui_Keyboard1 = NULL;

}
