// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PORUKE1_H
#define UI_PORUKE1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Poruke1
extern void ui_Poruke1_screen_init(void);
extern void ui_Poruke1_screen_destroy(void);
extern lv_obj_t * ui_Poruke1;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

