// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_PORUKESCREEN_H
#define UI_PORUKESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PorukeScreen
extern void ui_PorukeScreen_screen_init(void);
extern void ui_PorukeScreen_screen_destroy(void);
extern lv_obj_t * ui_PorukeScreen;
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_BackButtonMsg(lv_event_t * e);
extern lv_obj_t * ui_BackButtonMsg;

// Unread message counter — used by HomePage badge
extern int  poruke_get_unread(void);
extern void poruke_clear_unread(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
