// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_SOSScreen = NULL;
// event funtions

// build funtions

void ui_SOSScreen_screen_init(void)
{
    ui_SOSScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SOSScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_SOSScreen_screen_destroy(void)
{
    if(ui_SOSScreen) lv_obj_del(ui_SOSScreen);

    // NULL screen variables
    ui_SOSScreen = NULL;

}
