// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_SOSSCREEN_H
#define UI_SOSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SOSScreen
extern void ui_SOSScreen_screen_init(void);
extern void ui_SOSScreen_screen_destroy(void);
extern lv_obj_t * ui_SOSScreen;
extern void ui_event_GumbSOS(lv_event_t * e);
extern lv_obj_t * ui_GumbSOS;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

