// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_TETRISSCREEN_H
#define UI_TETRISSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TetrisScreen
extern void ui_TetrisScreen_screen_init(void);
extern void ui_TetrisScreen_screen_destroy(void);
extern lv_obj_t * ui_TetrisScreen;
extern lv_obj_t * ui_Panel1;
extern void ui_event_ImgButton15(lv_event_t * e);
extern lv_obj_t * ui_ImgButton15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

