// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_TemperaturaScreen = NULL;
lv_obj_t * ui_BackButtonTemp = NULL;
lv_obj_t * ui_Panel3 = NULL;
// event funtions
void ui_event_BackButtonTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage2_screen_init);
    }
}

// build funtions

void ui_TemperaturaScreen_screen_init(void)
{
    ui_TemperaturaScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TemperaturaScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TemperaturaScreen, &ui_img_527192083, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonTemp = lv_imgbtn_create(ui_TemperaturaScreen);
    lv_obj_set_width(ui_BackButtonTemp, 30);
    lv_obj_set_height(ui_BackButtonTemp, 30);
    lv_obj_set_x(ui_BackButtonTemp, -140);
    lv_obj_set_y(ui_BackButtonTemp, -100);
    lv_obj_set_align(ui_BackButtonTemp, LV_ALIGN_CENTER);

    ui_Panel3 = lv_obj_create(ui_TemperaturaScreen);
    lv_obj_set_width(ui_Panel3, 200);
    lv_obj_set_height(ui_Panel3, 150);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xAB0107), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackButtonTemp, ui_event_BackButtonTemp, LV_EVENT_ALL, NULL);

}

void ui_TemperaturaScreen_screen_destroy(void)
{
    if(ui_TemperaturaScreen) lv_obj_del(ui_TemperaturaScreen);

    // NULL screen variables
    ui_TemperaturaScreen = NULL;
    ui_BackButtonTemp = NULL;
    ui_Panel3 = NULL;

}
