// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_TetrisScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
// event funtions

// build funtions

void ui_TetrisScreen_screen_init(void)
{
    ui_TetrisScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TetrisScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_TetrisScreen);
    lv_obj_set_width(ui_Panel1, 110);
    lv_obj_set_height(ui_Panel1, 220);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_TetrisScreen_screen_destroy(void)
{
    if(ui_TetrisScreen) lv_obj_del(ui_TetrisScreen);

    // NULL screen variables
    ui_TetrisScreen = NULL;
    ui_Panel1 = NULL;

}
