// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_TEMPERATURASCREEN_H
#define UI_TEMPERATURASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TemperaturaScreen
extern void ui_TemperaturaScreen_screen_init(void);
extern void ui_TemperaturaScreen_screen_destroy(void);
extern lv_obj_t * ui_TemperaturaScreen;
extern void ui_event_BackButtonTemp(lv_event_t * e);
extern lv_obj_t * ui_BackButtonTemp;
extern lv_obj_t * ui_Panel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

